export const commands = [
  "Open File",
  "Save File",
  "Close Tab",
  "Go to Line",
  "Toggle Sidebar",
  "Find in Files",
  "Replace",
  "Undo",
  "Redo",
  "Command Palette",
  "Open Recent",
  "New Window",
  "Split Editor",
  "Toggle Terminal",
  "Format Document",
  "Rename Symbol",
  "Go to Definition",
  "Go to References",
  "Toggle Word Wrap",
  "Show Extensions",
  "Open Settings",
  "Open Keyboard Shortcuts",
  "Toggle Minimap",
  "Focus Explorer",
  "Focus Editor",
  "Focus Terminal",
  "Next Tab",
  "Previous Tab",
  "Close Editor",
  "Reopen Closed Editor",
  "Open Folder",
  "Save All",
  "Close Folder",
  "Select Theme",
  "Debug: Start",
  "Debug: Stop",
  "Run Task",
  "Show Problems",
  "Quick Open",
  "Toggle Full Screen",
]